baseURL = 'https://LilPapers.github.io/'
languageCode = 'ko-kr'
title = 'LilPapers'
theme = 'PaperMod'

[params]
    env = 'production'
    title = 'LilPapers main'
    description = '...'
    # PaperMod 전용 설정들을 여기에 추가할 수 있습니다.